/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.warnmychild.child.kotlin.DBHelper;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType ChildInfo.
 *
 * @since 2021-05-03
 */
@PrimaryKeys({"ChildID"})
public final class ChildInfo extends CloudDBZoneObject {
    private String ChildID;

    private String ChildName;

    private String ChildEmail;

    private String ParentID;

    public ChildInfo() {
        super(ChildInfo.class);
    }

    public void setChildID(String ChildID) {
        this.ChildID = ChildID;
    }

    public String getChildID() {
        return ChildID;
    }

    public void setChildName(String ChildName) {
        this.ChildName = ChildName;
    }

    public String getChildName() {
        return ChildName;
    }

    public void setChildEmail(String ChildEmail) {
        this.ChildEmail = ChildEmail;
    }

    public String getChildEmail() {
        return ChildEmail;
    }

    public void setParentID(String ParentID) {
        this.ParentID = ParentID;
    }

    public String getParentID() {
        return ParentID;
    }

}
