/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.warnmychild.child.kotlin.DBHelper;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType ParentInfo.
 *
 * @since 2021-05-03
 */
@PrimaryKeys({"ParentID"})
public final class ParentInfo extends CloudDBZoneObject {
    private String ParentID;

    private String ParentName;

    private String EmailID;

    private String ChildIDs;

    public ParentInfo() {
        super(ParentInfo.class);
    }

    public void setParentID(String ParentID) {
        this.ParentID = ParentID;
    }

    public String getParentID() {
        return ParentID;
    }

    public void setParentName(String ParentName) {
        this.ParentName = ParentName;
    }

    public String getParentName() {
        return ParentName;
    }

    public void setEmailID(String EmailID) {
        this.EmailID = EmailID;
    }

    public String getEmailID() {
        return EmailID;
    }

    public void setChildIDs(String ChildIDs) {
        this.ChildIDs = ChildIDs;
    }

    public String getChildIDs() {
        return ChildIDs;
    }

}
