/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.warnmychild.child.kotlin.DBHelper;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType testObjectTypeName.
 *
 * @since 2021-05-03
 */
@PrimaryKeys({"field1"})
@Indexes({"index1:field1,field2", "index2:field1,field2,field3"})
public final class testObjectTypeName extends CloudDBZoneObject {
    private String field1;

    private Long field2;

    private Integer field3;

    public testObjectTypeName() {
        super(testObjectTypeName.class);
    }

    public void setField1(String field1) {
        this.field1 = field1;
    }

    public String getField1() {
        return field1;
    }

    public void setField2(Long field2) {
        this.field2 = field2;
    }

    public Long getField2() {
        return field2;
    }

    public void setField3(Integer field3) {
        this.field3 = field3;
    }

    public Integer getField3() {
        return field3;
    }

}
